% test_phase21_repeatedSurveyQualityGates
% Regression tests for quality gating, reference choice, and RSS filtering.

clear; clc;

projectRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(projectRoot,"src")));

fprintf("Running Phase 21 repeated-survey quality-gate tests...\n");

[measurements,manifest] = qualityFixtureLocal();
aggregate = aggregateRepeatedTimingMeasurements( ...
    measurements,manifest,struct( ...
    "ReferencePCI",NaN,"ReferenceGSCN",7987, ...
    "MinRepeatsPerPosition",3, ...
    "MaxTimingStdNs",1000, ...
    "MinWindowsPerCaptureCell",2, ...
    "MinCapturesPerPositionCell",2));

assert(aggregate.ReferencePCI==446, ...
    "The strong repeatedly confirmed cell should be the reference.");
assert(~ismember(9,aggregate.ReliableCellSupport.PCI), ...
    "A one-window-per-capture cell must not count as reliable support.");
assert(any(aggregate.RejectedWindowMeasurements.PCI==9 & ...
    aggregate.RejectedWindowMeasurements.RejectionReason== ...
    "TOO_FEW_WINDOWS_IN_CAPTURE"));
assert(any(aggregate.RejectedWindowMeasurements.PCI==559 & ...
    aggregate.RejectedWindowMeasurements.RejectionReason== ...
    "TIMING_SPREAD_ABOVE_LIMIT"));

bootstrapResult = struct();
bootstrapResult.WindowMeasurements = measurements;
bootstrapResult.PowerObservations = powerFixtureLocal(measurements);
bootstrapResult.ObservationSummary = table();
bootstrapResult.LoadSummary = table();
result = bootstrapResult; %#ok<NASGU>
bootstrapPath = fullfile(tempdir,"phase21_repeat_bootstrap.mat");
save(bootstrapPath,"result");
cleanup = onCleanup(@()deleteIfPresentLocal(bootstrapPath)); %#ok<NASGU>

survey = runRepeatedPositionSurvey(manifest,struct( ...
    "Cache",struct("BootstrapResultPath",bootstrapPath,"Enable",false), ...
    "Repeats",struct("ReferencePCI",NaN,"ReferenceGSCN",7987, ...
        "MinRepeatsPerPosition",3,"MaxTimingStdNs",1000, ...
        "WindowStartSeconds",[0.05 0.31 0.57], ...
        "MinWindowsPerCaptureCell",2, ...
        "MinCapturesPerPositionCell",2), ...
    "Survey",struct("MinCaptures",3,"NumRandomStarts",1), ...
    "RSS",struct("MinReliablePositions",3, ...
        "MinReliableCaptures",6), ...
    "EnableRSSPlanning",false,"Verbose",false));

assert(survey.ReferencePCI==446);
assert(~ismember(9,survey.PowerObservations.PCI));
assert(~ismember(777,survey.PowerObservations.PCI));
assert(all(ismember(unique(survey.PowerObservations.PCI),[446;559])));
assert(~isempty(survey.RejectedPowerObservations));

fprintf("Phase 21 repeated-survey quality-gate tests passed.\n");

function [measurements,manifest] = qualityFixtureLocal()
positions = 3;
repeats = 3;
windows = 3;
measurementParts = {};
manifestParts = {};
mc = 0;
rc = 0;
for p = 1:positions
    positionID = "p"+compose("%02d",p);
    for r = 1:repeats
        captureID = "quality_"+positionID+"_"+compose("%02d",r);
        rc = rc+1;
        manifestParts{rc,1} = table( ...
            captureID,positionID,r,"C:\fixture\"+captureID+"_iq.mat", ...
            "C:\fixture\"+captureID+"_meta.json", ...
            52+0.001*p,6+0.001*mod(p,2),30,5, ...
            'VariableNames',["CaptureID","PositionID","RepeatIndex", ...
            "IQPath","MetadataPath","RxLat","RxLon","RxAltM", ...
            "RxPositionUncertaintyM"]);
        for w = 1:windows
            observationID = captureID+"_w"+compose("%02d",w)+"_g7987";
            phase = mod(1e6*p+1e5*r+2e4*w,10e6);
            mc = mc+1;
            measurementParts{mc,1} = rowLocal( ...
                captureID,positionID,r,observationID,446,phase,20,0.8);
            timingStd = 30;
            if p==1 && r==1 && w==1
                timingStd = 200000;
            end
            mc = mc+1;
            measurementParts{mc,1} = rowLocal( ...
                captureID,positionID,r,observationID,559, ...
                mod(phase+250,10e6),timingStd,0.5);
            if w==1
                mc = mc+1;
                measurementParts{mc,1} = rowLocal( ...
                    captureID,positionID,r,observationID,9, ...
                    mod(phase+500,10e6),40,0.2);
            end
        end
    end
end
measurements = vertcat(measurementParts{:});
manifest = vertcat(manifestParts{:});
end

function row = rowLocal(captureID,positionID,repeatIndex, ...
        observationID,pci,phaseNs,timingStdNs,sssMetric)
cellKey = "GSCN7987_PCI"+string(pci);
row = table( ...
    captureID,positionID,repeatIndex,observationID,cellKey,7987,pci, ...
    phaseNs,timingStdNs,3.70272e9,0,3.70272e9,0.2,sssMetric,100, ...
    'VariableNames',["CaptureID","PositionID","RepeatIndex", ...
    "ObservationID","CellKey","GSCN","PCI","FramePhaseNs", ...
    "TimingStdNs","CenterFrequencyHz","SelectedSSBOffsetHz", ...
    "HypothesizedSSBCenterHz","MeanPSSMetric","MeanSSSMetric", ...
    "MeanCFOHz"]);
end

function power = powerFixtureLocal(measurements)
parts = cell(height(measurements)+height(unique( ...
    measurements.ObservationID)),1);
count = 0;
for k = 1:height(measurements)
    row = measurements(k,:);
    count = count+1;
    parts{count} = powerRowLocal(row,row.PCI,-50);
end
observations = unique(measurements(:, ...
    ["CaptureID","PositionID","RepeatIndex","ObservationID"]),"rows");
for k = 1:height(observations)
    row = observations(k,:);
    count = count+1;
    parts{count} = powerRowLocal(row,777,-30);
end
power = vertcat(parts{1:count});
end

function row = powerRowLocal(source,pci,powerDb)
cellKey = "GSCN7987_PCI"+string(pci);
row = table( ...
    source.CaptureID,source.PositionID,source.RepeatIndex, ...
    source.ObservationID,cellKey,7987,3.70272e9,0,pci, ...
    powerDb,-80,powerDb+80,1,"OK", ...
    'VariableNames',["CaptureID","PositionID","RepeatIndex", ...
    "ObservationID","CellKey","GSCN","SSBCenterHz", ...
    "DigitalShiftHz","PCI","PowerDbFS","NoiseDbFS","SNRdB", ...
    "NumDetections","QualityFlag"]);
end

function deleteIfPresentLocal(path)
if isfile(path)
    delete(path);
end
end
