% run_identifiability_diagnostics
% Refit the processed P01-P15 survey and export multi-start and scaled
% Jacobian diagnostics. No IQ data or B210 hardware are used.

clear; clc;

projectRoot = fileparts(mfilename("fullpath"));
addpath(genpath(fullfile(projectRoot,"src")));

reportDir = fullfile(projectRoot,"reports","real_survey");
base = "b210_stationary_repeat_survey_20260621";
measurements = readtable( ...
    fullfile(reportDir,base+"_geometry_measurements.csv"), ...
    "TextType","string");
positions = readtable( ...
    fullfile(reportDir,base+"_positions.csv"), ...
    "TextType","string");

opts = struct( ...
    "SyncThresholdNs",1000, ...
    "ReferencePCI",446, ...
    "NumRandomStarts",48, ...
    "RequireInstabilityAssessableForPass",false);
result = noLocationSurveyCheck(measurements,positions,opts);

fit = result.FitInfo;
starts = fit.StartDiagnostics;
numeric = fit.NumericalDiagnostics;

fprintf("\nScaled-Jacobian numerical diagnostics:\n");
fprintf("  rank: %d / %d\n",numeric.NumericalRank,numeric.NumParameters);
fprintf("  cond(Jscaled): %.6g\n",numeric.ConditionNumber);
fprintf("  rcond(Jscaled''*Jscaled): %.6g\n",numeric.NormalMatrixRcond);
fprintf("  starts: %d valid, %d near-optimal\n", ...
    starts.NumValidStarts,starts.NumNearOptimalStarts);
fprintf("  maximum near-optimal offset spread: %.3f ns\n", ...
    starts.MaxNearOptimalOffsetSpreadNs);
disp(starts.PerTarget);

writetable(starts.PerTarget, ...
    fullfile(reportDir,base+"_multistart_consensus.csv"));
singularTable = table((1:numel(numeric.SingularValues)).', ...
    numeric.SingularValues, ...
    'VariableNames',["Index","SingularValue"]);
writetable(singularTable, ...
    fullfile(reportDir,base+"_scaled_jacobian_singular_values.csv"));
weakDirection = table(numeric.ParameterNames, ...
    numeric.WeakestRightSingularVector, ...
    'VariableNames',["Parameter","WeakDirectionCoefficient"]);
writetable(weakDirection, ...
    fullfile(reportDir,base+"_scaled_jacobian_weak_direction.csv"));
save(fullfile(reportDir,base+"_identifiability_diagnostics.mat"), ...
    "result");
