% run_jackknife_from_processed
% Leave-one-contributing-position-out sensitivity analysis using the
% processed P01-P15 geometry tables. No IQ data or B210 hardware are used.

clear; clc;

projectRoot = fileparts(mfilename("fullpath"));
addpath(genpath(fullfile(projectRoot,"src")));

reportDir = fullfile(projectRoot,"reports","real_survey");
base = "b210_stationary_repeat_survey_20260621";
measurements = readtable( ...
    fullfile(reportDir,base+"_geometry_measurements.csv"), ...
    "TextType","string");
positions = readtable( ...
    fullfile(reportDir,base+"_positions.csv"), ...
    "TextType","string");

surveyOpts = struct( ...
    "SyncThresholdNs",1000, ...
    "ReferencePCI",446, ...
    "NumRandomStarts",24, ...
    "RequireInstabilityAssessableForPass",false);
jackknifeOpts = struct( ...
    "SyncThresholdNs",1000, ...
    "OnlyMeasuredPositions",true);

stability = jackknifeSurveyStability( ...
    measurements,positions,surveyOpts,jackknifeOpts);

fprintf("\nJackknife positions used: %d of %d\n", ...
    stability.NumFolds,stability.NumInputPositions);
if ~isempty(stability.UnusedPositionIDs)
    fprintf("Positions without accepted geometry rows: %s\n", ...
        strjoin(stability.UnusedPositionIDs,", "));
end
disp(stability.PerCell);

writetable(stability.PerCell, ...
    fullfile(reportDir,base+"_jackknife_per_cell.csv"));
writetable(stability.Folds, ...
    fullfile(reportDir,base+"_jackknife_folds.csv"));
writetable(stability.Baseline, ...
    fullfile(reportDir,base+"_jackknife_baseline.csv"));

save(fullfile(reportDir,base+"_jackknife.mat"),"stability");
