function reportPaths = generateSurveyReport(result, outputDir, baseName)
%generateSurveyReport Write no-location survey results to MAT/CSV/JSON.

arguments
    result struct
    outputDir (1,1) string
    baseName (1,1) string = "rdi_no_location_survey_report"
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

matPath = fullfile(outputDir, baseName + ".mat");
jsonPath = fullfile(outputDir, baseName + "_summary.json");
markdownPath = fullfile(outputDir, baseName + "_human_summary.md");
timingCsvPath = fullfile(outputDir, baseName + "_timing_estimates.csv");
relativeCsvPath = fullfile(outputDir, baseName + "_relative_measurements.csv");
powerCsvPath = fullfile(outputDir, baseName + "_rss_power_measurements.csv");
rssPriorCsvPath = fullfile(outputDir, baseName + "_rss_priors.csv");
stopCsvPath = fullfile(outputDir, baseName + "_suggested_receiver_stops.csv");

save(matPath, "result", "-v7.3");

summary = struct();
summary.Mode = result.Mode;
summary.Statement = result.Statement;
if isfield(result, "VerdictBasis")
    summary.VerdictBasis = result.VerdictBasis;
else
    summary.VerdictBasis = "Synchronization verdict uses timing-only evidence.";
end
if isfield(result, "ExcludedFromVerdict")
    summary.ExcludedFromVerdict = result.ExcludedFromVerdict;
else
    summary.ExcludedFromVerdict = ["TDD pattern energy feedback","Special-slot energy feedback","RSS/RSSI planning feedback","CFO diagnostic reporting"];
end
summary.FitInfo = result.FitInfo;
summary.SyntheticValidationArtifact = isSyntheticArtifactLocal(result);
summary.Thresholds = thresholdsFromResultLocal(result);
summary.NumTimingEstimates = safeHeightLocal(result, "TimingEstimates");
summary.NumPowerMeasurements = safeHeightLocal(result, "PowerTable");
summary.NumRssPriors = safeHeightLocal(result, "RssPriors");
summary.NumSuggestedReceiverStops = safeHeightLocal(result, "SuggestedReceiverStops");
if isfield(result, "RssPlanningStatement")
    summary.RssPlanningStatement = result.RssPlanningStatement;
else
    summary.RssPlanningStatement = "RSS-assisted planning was not run.";
end
if isfield(result, "DecisionTable") && istable(result.DecisionTable) && ~isempty(result.DecisionTable)
    summary.Verdicts = table2struct(result.DecisionTable(:, ["PCI","SurveyRole","Verdict"]));
else
    summary.Verdicts = struct([]);
end

fid = fopen(jsonPath, "w");
if fid < 0
    error("generateSurveyReport:OpenFailed", "Could not write JSON report: %s", jsonPath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", jsonencode(summary, "PrettyPrint", true));
clear cleanup;

writeHumanSummaryLocal(markdownPath, result, summary);

if isfield(result, "TimingEstimates") && istable(result.TimingEstimates)
    writetable(result.TimingEstimates, timingCsvPath);
else
    writetable(table(), timingCsvPath);
end

if isfield(result, "RelativeMeasurements") && istable(result.RelativeMeasurements)
    writetable(result.RelativeMeasurements, relativeCsvPath);
else
    writetable(table(), relativeCsvPath);
end

if isfield(result, "PowerTable") && istable(result.PowerTable)
    writetable(result.PowerTable, powerCsvPath);
else
    writetable(table(), powerCsvPath);
end

if isfield(result, "RssPriors") && istable(result.RssPriors)
    writetable(result.RssPriors, rssPriorCsvPath);
else
    writetable(table(), rssPriorCsvPath);
end

if isfield(result, "SuggestedReceiverStops") && istable(result.SuggestedReceiverStops)
    writetable(result.SuggestedReceiverStops, stopCsvPath);
else
    writetable(table(), stopCsvPath);
end

reportPaths = struct();
reportPaths.MAT = matPath;
reportPaths.JSON = jsonPath;
reportPaths.Markdown = markdownPath;
reportPaths.TimingCSV = timingCsvPath;
reportPaths.RelativeMeasurementsCSV = relativeCsvPath;
reportPaths.RssPowerCSV = powerCsvPath;
reportPaths.RssPriorsCSV = rssPriorCsvPath;
reportPaths.SuggestedReceiverStopsCSV = stopCsvPath;

end

function writeHumanSummaryLocal(markdownPath, result, summary)
fid = fopen(markdownPath, "w");
if fid < 0
    error("generateSurveyReport:OpenFailed", ...
        "Could not write Markdown report: %s", markdownPath);
end
cleanup = onCleanup(@() fclose(fid));

fprintf(fid, "# Passive Relative Synchronization Survey Summary\n\n");
fprintf(fid, "Generated by `generateSurveyReport`.\n\n");

if isSyntheticArtifactLocal(result)
    fprintf(fid, "> **Synthetic validation artifact, not real measurement data.**\n\n");
end

fprintf(fid, "## Assessment Type\n\n");
fprintf(fid, "This report is for **relative synchronization assessment** using internally clocked USRP B210 IQ captures. ");
fprintf(fid, "It does not certify absolute UTC phase compliance, because the B210 captures are not disciplined by GPSDO, GNSS 10 MHz + 1 PPS, or another absolute timing reference.\n\n");

fprintf(fid, "## Overall Result\n\n");
if isfield(result, "FitInfo")
    fprintf(fid, "- Survey fit status: `%s`\n", string(result.FitInfo.Status));
    fprintf(fid, "- Survey fit reason: %s\n", string(result.FitInfo.Reason));
    fprintf(fid, "- Fit RMS: %.3f ns\n", safeNumberLocal(result.FitInfo, "FitRMSNs"));
    fprintf(fid, "- Condition number: %.3g\n", safeNumberLocal(result.FitInfo, "ConditionNumber"));
    if isfield(result.FitInfo, "ConditionNumberBasis")
        fprintf(fid, "- Condition-number basis: %s\n", ...
            string(result.FitInfo.ConditionNumberBasis));
    end
    if isfield(result.FitInfo, "NumericalDiagnostics") && ...
            isstruct(result.FitInfo.NumericalDiagnostics)
        numeric = result.FitInfo.NumericalDiagnostics;
        fprintf(fid, "- Numerical rank: %.0f of %.0f fitted parameters\n", ...
            safeNumberLocal(numeric, "NumericalRank"), ...
            safeNumberLocal(numeric, "NumParameters"));
        fprintf(fid, "- Normal-matrix reciprocal condition estimate: %.3g\n", ...
            safeNumberLocal(numeric, "NormalMatrixRcond"));
    end
    if isfield(result.FitInfo, "StartDiagnostics") && ...
            isstruct(result.FitInfo.StartDiagnostics)
        starts = result.FitInfo.StartDiagnostics;
        fprintf(fid, "- Valid optimization starts: %.0f; near-optimal starts: %.0f\n", ...
            safeNumberLocal(starts, "NumValidStarts"), ...
            safeNumberLocal(starts, "NumNearOptimalStarts"));
        fprintf(fid, "- Maximum target-offset spread among near-optimal starts: %.3f ns\n", ...
            safeNumberLocal(starts, "MaxNearOptimalOffsetSpreadNs"));
    end
    fprintf(fid, "- Reference PCI: %.0f\n\n", safeNumberLocal(result.FitInfo, "ReferencePCI"));
    fprintf(fid, "`OK` means that the optimizer returned a fitted solution. It does not by itself prove that the static offsets are uniquely or precisely identifiable; rank, conditioning, multi-start agreement, uncertainty, and sensitivity checks must also be considered.\n\n");
else
    fprintf(fid, "- Survey fit information was not available.\n\n");
end

fprintf(fid, "## Verdict Meaning\n\n");
fprintf(fid, "Verdict basis: %s\n\n", string(summary.VerdictBasis));
fprintf(fid, "Not used for synchronization verdict: %s.\n\n", strjoin(string(summary.ExcludedFromVerdict), ", "));
fprintf(fid, "- `PASS`: the combined worst-case relative timing envelope is below the configured desynchronization threshold with sufficient uncertainty margin.\n");
fprintf(fid, "- `SUSPECT`: static timing, instability, uncertainty, geometry, or model residuals are near a threshold.\n");
fprintf(fid, "- `FAIL`: the combined worst-case relative timing envelope exceeds a configured desynchronization threshold after uncertainty handling.\n");
fprintf(fid, "- `NOT_ASSESSABLE`: the capture/survey geometry does not contain enough evidence for a strict decision.\n\n");
if isfield(result,"StationaryInstability")
    fprintf(fid, "The combined envelope is `abs(static offset) + maximum stationary relative timing deviation`. ");
    fprintf(fid, "The stationary deviation comes from repeated fixed-position captures. Survey-model residuals are reported separately as fit-consistency evidence and are not labelled transmitter jitter.\n\n");
else
    fprintf(fid, "The combined envelope is `abs(static offset) + max absolute post-fit residual`. Static offset, RMS instability, and peak-to-peak instability are also reported separately as diagnostic metrics.\n\n");
end

fprintf(fid, "Timing thresholds used:\n\n");
thresholds = thresholdsFromResultLocal(result);
fprintf(fid, "- Static relative timing desynchronization threshold: %s ns\n", formatThresholdLocal(thresholds.SyncThresholdNs));
if isfinite(thresholds.WarningOffsetNs)
    fprintf(fid, "- Static warning threshold: %s ns\n", formatThresholdLocal(thresholds.WarningOffsetNs));
else
    fprintf(fid, "- Static warning mode: uncertainty interval overlaps the desynchronization threshold\n");
end
fprintf(fid, "- Static hard-fail threshold: %s ns\n", formatThresholdLocal(thresholds.HardFailOffsetNs));
fprintf(fid, "- Instability RMS warning/fail: %s / %s ns\n", ...
    formatThresholdLocal(thresholds.WarningInstabilityRmsNs), ...
    formatThresholdLocal(thresholds.FailInstabilityRmsNs));
fprintf(fid, "- Instability peak-to-peak warning/fail/hard-fail: %s / %s / %s ns\n", ...
    formatThresholdLocal(thresholds.WarningInstabilityPeakToPeakNs), ...
    formatThresholdLocal(thresholds.FailInstabilityPeakToPeakNs), ...
    formatThresholdLocal(thresholds.HardFailInstabilityPeakToPeakNs));
fprintf(fid, "- Uncertainty margin: %.0f sigma\n\n", thresholds.UncertaintySigmaMultiplier);

fprintf(fid, "## Per-PCI Timing Verdicts\n\n");
if isfield(result, "DecisionTable") && istable(result.DecisionTable) && height(result.DecisionTable) > 0
    fprintf(fid, "%s\n\n", tableToMarkdownLocal(result.DecisionTable));
else
    fprintf(fid, "No per-PCI timing verdict table was available.\n\n");
end

fprintf(fid, "## RSS-Assisted Planning\n\n");
if isfield(result, "RssPriors") && istable(result.RssPriors) && height(result.RssPriors) > 0
    fprintf(fid, "RSS-assisted planning was run. These priors are **rough planning aids only** and are not used for strict timing verdicts.\n\n");
    fprintf(fid, "- RSS power rows: %.0f\n", safeFieldLocal(summary, "NumPowerMeasurements"));
    fprintf(fid, "- RSS priors: %.0f\n", safeFieldLocal(summary, "NumRssPriors"));
    fprintf(fid, "- Suggested receiver stops: %.0f\n\n", safeFieldLocal(summary, "NumSuggestedReceiverStops"));
else
    fprintf(fid, "RSS-assisted planning was not run, or no usable RSS priors were produced.\n\n");
end

fprintf(fid, "## What This Report Cannot Conclude\n\n");
fprintf(fid, "- It cannot detect a common timing shift shared by all visible gNBs.\n");
fprintf(fid, "- It cannot detect common-mode timing movement that is present identically in every visible PCI inside a capture.\n");
fprintf(fid, "- It cannot assess a single visible gNB in isolation.\n");
fprintf(fid, "- It cannot prove absolute UTC compliance without external timing hardware.\n");
fprintf(fid, "- It cannot distinguish all NLOS/multipath timing bias from true transmit timing offset.\n");
fprintf(fid, "- It cannot assess gNBs outside the captured bandwidth or below detection SNR.\n\n");

fprintf(fid, "## Thesis Wording\n\n");
fprintf(fid, "Suggested wording: `The implemented tool verifies relative frame timing and TDD-pattern evidence between simultaneously visible private-network gNBs using passive B210 IQ captures. With an internal-clock-only B210, the method does not claim absolute UTC timing compliance. PASS/FAIL results therefore refer to relative synchronization within the measured survey geometry.`\n");
end

function tf = isSyntheticArtifactLocal(result)
tf = false;
if isfield(result, "IsSynthetic") && logical(result.IsSynthetic)
    tf = true;
elseif isfield(result, "ArtifactType") && contains(upper(string(result.ArtifactType)), "SYNTHETIC")
    tf = true;
elseif isfield(result, "Measurements") && istable(result.Measurements) && ...
        ismember("SyntheticArtifact", string(result.Measurements.Properties.VariableNames)) && ...
        any(logical(result.Measurements.SyntheticArtifact))
    tf = true;
end
end

function thresholds = thresholdsFromResultLocal(result)
thresholds = struct();
thresholds.WarningOffsetNs = NaN;
thresholds.FailOffsetNs = 1000;
thresholds.HardFailOffsetNs = Inf;
thresholds.SyncThresholdNs = thresholds.FailOffsetNs;
thresholds.UncertaintySigmaMultiplier = 3;
thresholds.MaxFitRMSNsForPass = 0.20 * thresholds.FailOffsetNs;
thresholds.MaxBiasUncertaintyForPassNs = 0.20 * thresholds.FailOffsetNs;
thresholds.WarningInstabilityRmsNs = NaN;
thresholds.FailInstabilityRmsNs = NaN;
thresholds.WarningInstabilityPeakToPeakNs = NaN;
thresholds.FailInstabilityPeakToPeakNs = NaN;
thresholds.HardFailInstabilityPeakToPeakNs = Inf;
if ~isfield(result, "FitInfo")
    return;
end
names = fieldnames(thresholds);
for k = 1:numel(names)
    name = names{k};
    if isfield(result.FitInfo, name)
        thresholds.(name) = result.FitInfo.(name);
    end
end
end

function n = safeHeightLocal(s, fieldName)
if isfield(s, fieldName) && istable(s.(fieldName))
    n = height(s.(fieldName));
else
    n = 0;
end
end

function value = safeNumberLocal(s, fieldName)
if isfield(s, fieldName)
    value = double(s.(fieldName));
else
    value = NaN;
end
end

function value = safeFieldLocal(s, fieldName)
if isfield(s, fieldName)
    value = s.(fieldName);
else
    value = 0;
end
end

function md = tableToMarkdownLocal(tbl)
names = string(tbl.Properties.VariableNames);
lines = strings(0,1);
lines(end+1,1) = "| " + strjoin(names, " | ") + " |";
lines(end+1,1) = "| " + strjoin(repmat("---", 1, numel(names)), " | ") + " |";
for r = 1:height(tbl)
    vals = strings(1, numel(names));
    for c = 1:numel(names)
        vals(c) = printableValueLocal(tbl.(names(c))(r));
    end
    lines(end+1,1) = "| " + strjoin(vals, " | ") + " |"; %#ok<AGROW>
end
md = strjoin(lines, newline);
end

function txt = printableValueLocal(value)
if isstring(value)
    txt = value;
elseif iscell(value)
    txt = string(value{1});
elseif islogical(value)
    txt = string(value);
elseif isnumeric(value)
    if isinf(value)
        txt = "Inf";
    elseif isnan(value)
        txt = "NaN";
    else
        txt = string(round(value, 3));
    end
else
    txt = string(value);
end
txt = replace(txt, "|", "/");
end

function txt = formatThresholdLocal(value)
if isnan(value)
    txt = "disabled";
elseif isinf(value)
    txt = "disabled";
else
    txt = string(round(value, 3));
end
end
