function report = validateB210CampaignCapture(cfg, actualSampleCount, overrunCount)
%validateB210CampaignCapture Enforce the fixed thesis survey capture profile.
%
% Call with cfg only before creating the receiver. Call again with the
% acquired sample and overrun counts before saving any capture artifacts.

arguments
    cfg struct
    actualSampleCount = []
    overrunCount = []
end

expected = struct( ...
    "MasterClockRateHz", 30.72e6, ...
    "DecimationFactor", 1, ...
    "SampleRateHz", 30.72e6, ...
    "BandwidthHz", 30e6, ...
    "DurationSeconds", 1.0, ...
    "SamplesPerFrame", 153600, ...
    "CenterFrequencyHz", 3.70272e9, ...
    "Gain", 45);

names = fieldnames(expected);
for k = 1:numel(names)
    name = names{k};
    if ~isfield(cfg, name) || ~isscalar(cfg.(name)) || ...
            ~isfinite(cfg.(name)) || cfg.(name) ~= expected.(name)
        error("B210Capture:CampaignProfileMismatch", ...
            "%s must equal %.12g for the survey_20260621 campaign.", ...
            name, expected.(name));
    end
end

if ~isfield(cfg, "ActualSampleRateHz") || isempty(cfg.ActualSampleRateHz)
    actualSampleRateHz = cfg.SampleRateHz;
else
    actualSampleRateHz = cfg.ActualSampleRateHz;
end
if actualSampleRateHz ~= expected.SampleRateHz
    error("B210Capture:SampleRateMismatch", ...
        "The B210 must report exactly %.0f Hz; reported %.12g Hz.", ...
        expected.SampleRateHz, actualSampleRateHz);
end

if ~isfield(cfg, "CampaignID") || string(cfg.CampaignID) ~= "survey_20260621"
    error("B210Capture:CampaignIDMismatch", ...
        "CampaignID must be survey_20260621.");
end
if ~isfield(cfg,"PositionID") || isempty(regexp( ...
        char(string(cfg.PositionID)),"^p[0-9]+$","once"))
    error("B210Capture:PositionIDMismatch", ...
        "PositionID must use pNN naming, for example p01.");
end
if ~isfield(cfg,"RepeatIndex") || ~isscalar(cfg.RepeatIndex) || ...
        ~isfinite(cfg.RepeatIndex) || cfg.RepeatIndex < 1 || ...
        cfg.RepeatIndex ~= round(cfg.RepeatIndex)
    error("B210Capture:RepeatIndexInvalid", ...
        "RepeatIndex must be a positive integer.");
end
expectedCaptureID = string(cfg.CampaignID) + "_" + ...
    string(cfg.PositionID) + "_" + compose("%02d",cfg.RepeatIndex);
if ~isfield(cfg,"CaptureID") || string(cfg.CaptureID) ~= expectedCaptureID
    error("B210Capture:CaptureIDMismatch", ...
        "CaptureID must equal %s for the configured position and repeat.", ...
        expectedCaptureID);
end

if ~isfield(cfg, "RxLat") || ~isfinite(cfg.RxLat) || ...
        cfg.RxLat < -90 || cfg.RxLat > 90 || ...
        ~isfield(cfg, "RxLon") || ~isfinite(cfg.RxLon) || ...
        cfg.RxLon < -180 || cfg.RxLon > 180
    error("B210Capture:MissingGPS", ...
        "Enter finite decimal-degree RxLat and RxLon before capturing.");
end
if ~isfield(cfg, "RxAltM") || ~isfinite(cfg.RxAltM)
    error("B210Capture:MissingAltitude", ...
        "Enter the measured receiver altitude before capturing.");
end
if ~isfield(cfg, "RxPositionUncertaintyM") || ...
        ~isfinite(cfg.RxPositionUncertaintyM) || cfg.RxPositionUncertaintyM <= 0
    error("B210Capture:MissingPositionUncertainty", ...
        "RxPositionUncertaintyM must be a positive finite value.");
end

expectedSampleCount = round(expected.SampleRateHz * expected.DurationSeconds);
if ~isempty(overrunCount)
    if ~isscalar(overrunCount) || ~isfinite(overrunCount) || overrunCount ~= 0
        error("B210Capture:RejectedOverrun", ...
            "Capture rejected: expected zero overruns, observed %.0f.", ...
            overrunCount);
    end
end
if ~isempty(actualSampleCount)
    if ~isscalar(actualSampleCount) || ~isfinite(actualSampleCount) || ...
            actualSampleCount ~= expectedSampleCount
        error("B210Capture:RejectedSampleCount", ...
            "Capture rejected: expected %d samples, observed %.0f.", ...
            expectedSampleCount, actualSampleCount);
    end
end

report = struct();
report.IsValid = true;
report.ExpectedSampleCount = expectedSampleCount;
report.ActualSampleCount = actualSampleCount;
report.OverrunCount = overrunCount;
report.ExpectedSampleRateHz = expected.SampleRateHz;
report.Statement = ...
    "Validated fixed-profile survey capture with continuous sample record.";
end
